# my own simple linear regression
this is my attempt at creating a linear regression model from scratch  
The model should have the same user interface as sklearn  
model = LinearRegression()  
model.fit(X, Y)  

for now, all we need is numpy

In [1]:
import numpy as np

In [2]:
class linear_regression_model():
    def __init__(self):
        self.theta = None
        self.J_histories = []
        self.theta = None
    
    def predict(self, X):
        X = np.hstack((np.ones((len(X),1)), X))
        predictions = X @ self.theta
        return predictions
        
    def fit(self, X:np.ndarray, y:np.ndarray, alpha = 0.01, num_iters = 10_000, y_lambda = 0):
        # add ones as an extra feature (at the beginning) in the input, to use this for the offset term
        X = np.hstack((np.ones((len(X),1)), X))
        
        if self.theta is None:
            self.theta = np.random.rand(X.shape[1], 1) # initialize 
        J_history = self.gradient_descent_regularised(X, y, self.theta, alpha, num_iters, y_lambda)
        self.J_histories.append(J_history)
    
    def compute_cost_add_offset(self, X, y):
        # add ones as an extra feature (at the beginning) in the input, to use this for the offset term
        X = np.hstack((np.ones((len(X),1)), X))
        if self.theta is None:
            self.theta = np.random.rand(X.shape[1], 1) # initialize 
        m = len(y) # number of training examples
        J = 1/(2*m) * sum((X @ self.theta - y)**2)
        return J
        
    def compute_cost(self, X, y):
        m = len(y) # number of training examples
        J = 1/(2*m) * sum((X @ self.theta - y)**2)
        return J
    
    def gradient_descent_regularised(self, X:np.ndarray, y:np.ndarray, theta:np.ndarray, alpha, num_iters, y_lambda):
        m = len(y)
        J_history = np.ndarray((num_iters))

        for i in range(num_iters):
            # % Instructions: Perform a single gradient step on the parameter vector
            # %               theta. 
            theta = self.theta
            self.theta = theta * ( 1 - alpha*y_lambda/m) - (alpha/m) * np.transpose(np.transpose( X @ theta - y ) @ X)
            
            # Save the cost J after every iteration    
            J_history[i] = self.compute_cost(X, y)
        
        return theta, J_history

In [3]:
model = linear_regression_model()

In [4]:
n_examples = 4
n_features = 2
X = np.random.rand(n_examples, n_features)
y = np.random.rand(n_examples, 1)

In [5]:
model.compute_cost_add_offset(X, y)

array([0.04930407])

In [6]:
model.fit(X, y)

In [7]:
model.compute_cost_add_offset(X, y)

array([0.02198488])

In [8]:
p0 = model.predict(X)
p0

array([[0.34572541],
       [0.87075286],
       [0.5711716 ],
       [0.48165509]])

In [9]:
from sklearn.linear_model import LinearRegression

In [10]:
sklearn_model = LinearRegression()
sklearn_model.fit(X,y)

LinearRegression()

In [11]:
p1 = sklearn_model.predict(X)
p1

array([[0.35067277],
       [0.87191898],
       [0.5628774 ],
       [0.48508411]])

## how much percent am I off?

In [12]:
(p1 - p0)*100

array([[ 0.49473585],
       [ 0.11661259],
       [-0.82941956],
       [ 0.34290178]])

In [13]:
my_diffs = []
baselines= []
for i in range(10):
    n_examples = 100
    n_features = 10
    X = np.random.rand(n_examples, n_features)
    y = np.random.rand(n_examples, 1)
    
    my_model = linear_regression_model()
    my_model.fit(X, y)
    p0 = model.predict(X)
    
    sk_model_1 = LinearRegression()
    sk_model_1.fit(X,y)
    sk1 = model.predict(X)
    
    sk_model_2 = LinearRegression()
    sk_model_2.fit(X,y)
    sk2 = model.predict(X)
    
    # we pretend that sk_1 is the ground truth and then we see, 
    # how far my model is of in comparison to the baseline sk_2
    
    my_diff = np.sqrt(sum((p0 - sk1)**2))
    my_diffs.append(my_diff)
    baseline = np.sqrt(sum((sk2 - sk1)**2))
    baselines.append(baseline)
    
    
    

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 11)